run:
  deadline: 1m
  issues-exit-code: 1
  tests: false
  skip-dirs:
    - vendor$
    - third_party$
    - testdata$
    - examples$

output:
  format: tab
  print-issued-lines: true
  print-linter-name: false

linters:
  enable-all: true
  disable:
    - maligned
    - prealloc

issues:
  exclude-rules:
    - linters:
      - lll
      source: "^//go:generate "
    - linters:
        - gomnd
      source: "os.exit"
    - linters:
        - gosec
      text: "G204"


linters-settings:
  funlen:
    lines: 80
    statements: 60
